import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center bg-black  p-24 h-full ">
          <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm ">
            <p className=" left-0 top-0 flex  justify-center border-b    border-neutral-800 text-zinc-300    from-inherit lg:static   w-auto   rounded-xl  border  p-4 bg-zinc-800/30">
              Simple web based wallet
            </p>
          </div>{" "}
          <Provider>
            <div className="p-5 h-full">{children}</div>
            <ToastContainer />
          </Provider>
        </main>
      </body>
    </html>
  );
}
